<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AuditFilesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('audit_files')->delete();
        
        \DB::table('audit_files')->insert(array (
            0 => 
            array (
                'id' => 1,
                'audit_form_id' => 1,
                'file' => 'audit_form_files/RNXN9hd1HpcJWHct3bEBaqEtSnhqCXE940tHSW8c.png',
                'file_type' => 'na',
                'file_name' => '637881058818827653.jpg',
                'file_size' => '10262',
                'file_ext' => 'jpg',
                'uploaded_by' => 3,
                'created_at' => '2023-01-24 12:00:16',
                'updated_at' => '2023-01-24 12:00:16',
            ),
            1 => 
            array (
                'id' => 2,
                'audit_form_id' => 1,
                'file' => 'audit_form_files/I1J9ujFq9d4jsH498ZUT3XSr20UmO4CYf7FD1ITx.pdf',
                'file_type' => 'na',
                'file_name' => 'Cover Letter.pdf',
                'file_size' => '110784',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-01-24 12:00:16',
                'updated_at' => '2023-01-24 12:00:16',
            ),
            2 => 
            array (
                'id' => 3,
                'audit_form_id' => 1,
                'file' => 'audit_form_files/zcXCL2KNENxJidiDolmkleLpoDUEcVOOlamXm1Iw.pptx',
                'file_type' => 'na',
                'file_name' => 'Cover Letter.pptx',
                'file_size' => '31706',
                'file_ext' => 'pptx',
                'uploaded_by' => 3,
                'created_at' => '2023-01-24 12:00:16',
                'updated_at' => '2023-01-24 12:00:16',
            ),
            3 => 
            array (
                'id' => 6,
                'audit_form_id' => 2,
                'file' => 'audit_form_files/3WKq95gW7ONz1Vn1URFYs1rfh0OEqoR2r8oAh0vO.xlsx',
                'file_type' => 'na',
                'file_name' => 'Book1.xlsx',
                'file_size' => '9665',
                'file_ext' => 'xlsx',
                'uploaded_by' => 1,
                'created_at' => '2023-01-24 12:16:11',
                'updated_at' => '2023-01-24 12:16:11',
            ),
            4 => 
            array (
                'id' => 7,
                'audit_form_id' => 2,
                'file' => 'audit_form_files/tA8WLu0xx2SWdUpCp1KDYkOcVZpLZvdaQXxZT1O5.xlsx',
                'file_type' => 'na',
                'file_name' => 'Copy of Fro Mr Rafeeq_.xlsx',
                'file_size' => '37375',
                'file_ext' => 'xlsx',
                'uploaded_by' => 1,
                'created_at' => '2023-01-24 12:16:11',
                'updated_at' => '2023-01-24 12:16:11',
            ),
            5 => 
            array (
                'id' => 8,
                'audit_form_id' => 3,
                'file' => 'audit_form_files/5mVqxZeuWbcdkP5XxCCpI7m5aI5LejXNz3RjAFnj.pdf',
                'file_type' => 'na',
                'file_name' => 'Cover Letter.pdf',
                'file_size' => '110784',
                'file_ext' => 'pdf',
                'uploaded_by' => 9,
                'created_at' => '2023-01-24 14:54:53',
                'updated_at' => '2023-01-24 14:54:53',
            ),
            6 => 
            array (
                'id' => 9,
                'audit_form_id' => 3,
                'file' => 'audit_form_files/27vOInmmRpBPDpE74uBDUlnhdT46MHQyjXnFTjLu.pptx',
                'file_type' => 'na',
                'file_name' => 'Cover Letter.pptx',
                'file_size' => '31706',
                'file_ext' => 'pptx',
                'uploaded_by' => 9,
                'created_at' => '2023-01-24 14:54:53',
                'updated_at' => '2023-01-24 14:54:53',
            ),
            7 => 
            array (
                'id' => 10,
                'audit_form_id' => 3,
                'file' => 'audit_form_files/t32bqI9cbQDFljfJ5VOH1YlhYAy65tib0EkhOYgq.pdf',
                'file_type' => 'na',
            'file_name' => 'Edris Malya (CV).pdf',
                'file_size' => '674065',
                'file_ext' => 'pdf',
                'uploaded_by' => 9,
                'created_at' => '2023-01-24 14:54:53',
                'updated_at' => '2023-01-24 14:54:53',
            ),
            8 => 
            array (
                'id' => 11,
                'audit_form_id' => 3,
                'file' => 'audit_form_files/7UxQRL1WVnj7589RV88t7xaBaZjiq1EmiGqozAf3.pdf',
                'file_type' => 'na',
                'file_name' => 'Edris Malya.pdf',
                'file_size' => '394165',
                'file_ext' => 'pdf',
                'uploaded_by' => 9,
                'created_at' => '2023-01-24 14:54:53',
                'updated_at' => '2023-01-24 14:54:53',
            ),
            9 => 
            array (
                'id' => 12,
                'audit_form_id' => 3,
                'file' => 'audit_form_files/Ck3vLE1vLqvu58Mi7ER4c1eqOViNM10A5FGZZhJs.jpg',
                'file_type' => 'na',
                'file_name' => 'edris.jpg',
                'file_size' => '673501',
                'file_ext' => 'jpg',
                'uploaded_by' => 9,
                'created_at' => '2023-01-24 14:54:53',
                'updated_at' => '2023-01-24 14:54:53',
            ),
            10 => 
            array (
                'id' => 13,
                'audit_form_id' => 3,
                'file' => 'audit_form_files/OMFrjDAaIhUGq2WwLjR07r6RFzc2AUamfSSYnyUb.pptx',
                'file_type' => 'na',
                'file_name' => 'Edris\'s Resume_2.pptx',
                'file_size' => '400244',
                'file_ext' => 'pptx',
                'uploaded_by' => 9,
                'created_at' => '2023-01-24 14:54:53',
                'updated_at' => '2023-01-24 14:54:53',
            ),
            11 => 
            array (
                'id' => 14,
                'audit_form_id' => 3,
                'file' => 'audit_form_files/EtDxn7kvF7C3WzWajzVLW2WoqFgfaCI1QAoIbd7a.pdf',
                'file_type' => 'na',
                'file_name' => 'Edris\'s Resume_Update.pdf',
                'file_size' => '394165',
                'file_ext' => 'pdf',
                'uploaded_by' => 9,
                'created_at' => '2023-01-24 14:54:53',
                'updated_at' => '2023-01-24 14:54:53',
            ),
            12 => 
            array (
                'id' => 15,
                'audit_form_id' => 4,
                'file' => 'audit_form_files/BArFYSMCrQpRvDvBHsmdZJQbBPfUnpXuJtzYH8ei.png',
                'file_type' => 'na',
                'file_name' => '637881058818827653.jpg',
                'file_size' => '10262',
                'file_ext' => 'jpg',
                'uploaded_by' => 3,
                'created_at' => '2023-01-26 09:36:34',
                'updated_at' => '2023-01-26 09:36:34',
            ),
            13 => 
            array (
                'id' => 16,
                'audit_form_id' => 4,
                'file' => 'audit_form_files/WjtXAxHylRjJVZDzZLZLEbDeCKAx42S4YrI3N4jT.pdf',
                'file_type' => 'na',
                'file_name' => 'Cover Letter.pdf',
                'file_size' => '110784',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-01-26 09:36:34',
                'updated_at' => '2023-01-26 09:36:34',
            ),
            14 => 
            array (
                'id' => 17,
                'audit_form_id' => 4,
                'file' => 'audit_form_files/hA83pKC18m8Wvu7XYOLhNSmlb69sj6YC4uvdVZol.pptx',
                'file_type' => 'na',
                'file_name' => 'Cover Letter.pptx',
                'file_size' => '31706',
                'file_ext' => 'pptx',
                'uploaded_by' => 3,
                'created_at' => '2023-01-26 09:36:34',
                'updated_at' => '2023-01-26 09:36:34',
            ),
            15 => 
            array (
                'id' => 18,
                'audit_form_id' => 4,
                'file' => 'audit_form_files/RfXTecb0EZCRxGHFw008qSbuwSDwHt3BsLsLEc3a.pdf',
                'file_type' => 'na',
            'file_name' => 'Edris Malya (CV).pdf',
                'file_size' => '674065',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-01-26 09:36:34',
                'updated_at' => '2023-01-26 09:36:34',
            ),
            16 => 
            array (
                'id' => 19,
                'audit_form_id' => 4,
                'file' => 'audit_form_files/M9U0RRhgf4kJsJgEJSblBrnIeF0haEUpHmU98jcI.pdf',
                'file_type' => 'na',
                'file_name' => 'Edris Malya.pdf',
                'file_size' => '394165',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-01-26 09:36:34',
                'updated_at' => '2023-01-26 09:36:34',
            ),
            17 => 
            array (
                'id' => 20,
                'audit_form_id' => 4,
                'file' => 'audit_form_files/IpEWwMKjhjjO3gPKp9IvppMZrHUwbWAwz99VmLXW.jpg',
                'file_type' => 'na',
                'file_name' => 'edris.jpg',
                'file_size' => '673501',
                'file_ext' => 'jpg',
                'uploaded_by' => 3,
                'created_at' => '2023-01-26 09:36:34',
                'updated_at' => '2023-01-26 09:36:34',
            ),
            18 => 
            array (
                'id' => 21,
                'audit_form_id' => 4,
                'file' => 'audit_form_files/ud2D6d9yJtoFF96VQ6sIrHHu6Tm214QFvxqrNCNG.pptx',
                'file_type' => 'na',
                'file_name' => 'Edris\'s Resume_2.pptx',
                'file_size' => '400244',
                'file_ext' => 'pptx',
                'uploaded_by' => 3,
                'created_at' => '2023-01-26 09:36:34',
                'updated_at' => '2023-01-26 09:36:34',
            ),
            19 => 
            array (
                'id' => 22,
                'audit_form_id' => 5,
                'file' => 'audit_form_files/FAWGjtzFmagcuVGWMCTpi9ZWd0J7Ksg2foJy52W5.pdf',
                'file_type' => 'na',
            'file_name' => 'Edris Malya (CV).pdf',
                'file_size' => '674065',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-02-02 11:50:10',
                'updated_at' => '2023-02-02 11:50:10',
            ),
            20 => 
            array (
                'id' => 23,
                'audit_form_id' => 5,
                'file' => 'audit_form_files/VpaDsrRRQIEzRcVNq8ykivHfM75yL7lUXE4Mc4rl.pdf',
                'file_type' => 'na',
                'file_name' => 'Edris Malya.pdf',
                'file_size' => '394165',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-02-02 11:50:10',
                'updated_at' => '2023-02-02 11:50:10',
            ),
            21 => 
            array (
                'id' => 24,
                'audit_form_id' => 6,
                'file' => 'audit_form_files/me7x9RyKcg1Lf2mEzYH3USNw6K796eaOFIj868ie.pptx',
                'file_type' => 'na',
                'file_name' => 'Cover Letter.pptx',
                'file_size' => '31706',
                'file_ext' => 'pptx',
                'uploaded_by' => 3,
                'created_at' => '2023-02-04 15:07:59',
                'updated_at' => '2023-02-04 15:07:59',
            ),
            22 => 
            array (
                'id' => 25,
                'audit_form_id' => 6,
                'file' => 'audit_form_files/IkzT5LsV3VidvdDRifuNw6TIdm4ElywuZHwb1I4J.pdf',
                'file_type' => 'na',
            'file_name' => 'Edris Malya (CV).pdf',
                'file_size' => '674065',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-02-04 15:07:59',
                'updated_at' => '2023-02-04 15:07:59',
            ),
            23 => 
            array (
                'id' => 26,
                'audit_form_id' => 6,
                'file' => 'audit_form_files/LSarwMjxQJzssYHg2qNnB9ZhOsRQuHzs1TnVrL9I.pdf',
                'file_type' => 'na',
                'file_name' => 'Edris Malya.pdf',
                'file_size' => '394165',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-02-04 15:07:59',
                'updated_at' => '2023-02-04 15:07:59',
            ),
            24 => 
            array (
                'id' => 27,
                'audit_form_id' => 7,
                'file' => 'audit_form_files/jpJnbCkAR4epJ6twgY0RYaExyEXQKJn0RgYDYANy.pdf',
                'file_type' => 'na',
                'file_name' => 'Edris\'s Resume_Update.pdf',
                'file_size' => '394165',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-02-05 09:42:44',
                'updated_at' => '2023-02-05 09:42:44',
            ),
            25 => 
            array (
                'id' => 28,
                'audit_form_id' => 7,
                'file' => 'audit_form_files/4g1Om5ykPhYIGoXEdQSVxzDbCO8BHBrVsx45ABIl.jpg',
                'file_type' => 'na',
                'file_name' => 'ID 1.jpeg',
                'file_size' => '156643',
                'file_ext' => 'jpeg',
                'uploaded_by' => 3,
                'created_at' => '2023-02-05 09:42:44',
                'updated_at' => '2023-02-05 09:42:44',
            ),
            26 => 
            array (
                'id' => 29,
                'audit_form_id' => 7,
                'file' => 'audit_form_files/fS04UHntCx9ZxXNfKqBZarGdD0vSzCIV8bpAyiO5.jpg',
                'file_type' => 'na',
                'file_name' => 'ID 2.jpeg',
                'file_size' => '118730',
                'file_ext' => 'jpeg',
                'uploaded_by' => 3,
                'created_at' => '2023-02-05 09:42:44',
                'updated_at' => '2023-02-05 09:42:44',
            ),
            27 => 
            array (
                'id' => 30,
                'audit_form_id' => 8,
                'file' => 'audit_form_files/Rwe8kqUvzP1lj69ZSrghI20gN6REh58wBAtgJHPA.pdf',
                'file_type' => 'na',
                'file_name' => 'Cover Letter.pdf',
                'file_size' => '110784',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-02-05 14:50:03',
                'updated_at' => '2023-02-05 14:50:03',
            ),
            28 => 
            array (
                'id' => 31,
                'audit_form_id' => 8,
                'file' => 'audit_form_files/Dw4vR7wRsofDU7iFcCyMVXpbLPiN7Io4kcCDe7DZ.pptx',
                'file_type' => 'na',
                'file_name' => 'Cover Letter.pptx',
                'file_size' => '31706',
                'file_ext' => 'pptx',
                'uploaded_by' => 3,
                'created_at' => '2023-02-05 14:50:04',
                'updated_at' => '2023-02-05 14:50:04',
            ),
            29 => 
            array (
                'id' => 32,
                'audit_form_id' => 8,
                'file' => 'audit_form_files/46YHPQrPYtaSxqIHOkCsiafY4uzoLAWX2hc8RqlH.pdf',
                'file_type' => 'na',
            'file_name' => 'Edris Malya (CV).pdf',
                'file_size' => '674065',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-02-05 14:50:04',
                'updated_at' => '2023-02-05 14:50:04',
            ),
            30 => 
            array (
                'id' => 33,
                'audit_form_id' => 8,
                'file' => 'audit_form_files/TZcxYY08WkQgz4lqO4WR5SUuqMRUVcR9RvPCsopq.pdf',
                'file_type' => 'na',
                'file_name' => 'Edris Malya.pdf',
                'file_size' => '394165',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-02-05 14:50:04',
                'updated_at' => '2023-02-05 14:50:04',
            ),
            31 => 
            array (
                'id' => 34,
                'audit_form_id' => 8,
                'file' => 'audit_form_files/MPKl9CQmp6P32j08cGVkRaB3bQsmKGTFqEvrfTkM.pdf',
                'file_type' => 'na',
                'file_name' => 'Edris\'s Resume_Update.pdf',
                'file_size' => '394165',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-02-05 14:50:04',
                'updated_at' => '2023-02-05 14:50:04',
            ),
            32 => 
            array (
                'id' => 35,
                'audit_form_id' => 8,
                'file' => 'audit_form_files/Sw46z75i7yigLNTnvOiFYrJUNewiXqrnRlhhEscU.jpg',
                'file_type' => 'na',
                'file_name' => 'ID 1.jpeg',
                'file_size' => '156643',
                'file_ext' => 'jpeg',
                'uploaded_by' => 3,
                'created_at' => '2023-02-05 14:50:04',
                'updated_at' => '2023-02-05 14:50:04',
            ),
            33 => 
            array (
                'id' => 36,
                'audit_form_id' => 8,
                'file' => 'audit_form_files/nK3Y1VW6oYYcHDPKRwFBbguQKdMIrSS6VYE5NX04.jpg',
                'file_type' => 'na',
                'file_name' => 'ID 2.jpeg',
                'file_size' => '118730',
                'file_ext' => 'jpeg',
                'uploaded_by' => 3,
                'created_at' => '2023-02-05 14:50:04',
                'updated_at' => '2023-02-05 14:50:04',
            ),
            34 => 
            array (
                'id' => 37,
                'audit_form_id' => 8,
                'file' => 'audit_form_files/Dtxu5fFnwo5ak9gegk5B6AnNfxwpq5v3ACACN5YX.jpg',
                'file_type' => 'na',
                'file_name' => 'passport.jpg',
                'file_size' => '912693',
                'file_ext' => 'jpg',
                'uploaded_by' => 3,
                'created_at' => '2023-02-05 14:50:04',
                'updated_at' => '2023-02-05 14:50:04',
            ),
            35 => 
            array (
                'id' => 38,
                'audit_form_id' => 9,
                'file' => 'audit_form_files/85QeJAtKzBI6ktzjpbmEdgR8RYj4XOzkK03xle3K.pdf',
                'file_type' => 'na',
                'file_name' => 'Cover Letter.pdf',
                'file_size' => '110784',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-02-05 15:19:37',
                'updated_at' => '2023-02-05 15:19:37',
            ),
            36 => 
            array (
                'id' => 39,
                'audit_form_id' => 10,
                'file' => 'audit_form_files/Xjs106NjZi1UVEmKFZtEjxdB936Q27pEo7B0A8wx.pdf',
                'file_type' => 'na',
                'file_name' => 'Cover Letter.pdf',
                'file_size' => '110784',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-02-06 09:08:30',
                'updated_at' => '2023-02-06 09:08:30',
            ),
            37 => 
            array (
                'id' => 40,
                'audit_form_id' => 10,
                'file' => 'audit_form_files/tuLtPF6Av2MlGxGZiWEqdzq7IPgubyyDNuy5lF6k.pptx',
                'file_type' => 'na',
                'file_name' => 'Cover Letter.pptx',
                'file_size' => '31706',
                'file_ext' => 'pptx',
                'uploaded_by' => 3,
                'created_at' => '2023-02-06 09:08:30',
                'updated_at' => '2023-02-06 09:08:30',
            ),
            38 => 
            array (
                'id' => 41,
                'audit_form_id' => 10,
                'file' => 'audit_form_files/ytFA3q9PGVnrtKx5Xt0R8tgeJMM0R1IQDcJ0zGEs.pdf',
                'file_type' => 'na',
            'file_name' => 'Edris Malya (CV).pdf',
                'file_size' => '674065',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-02-06 09:08:30',
                'updated_at' => '2023-02-06 09:08:30',
            ),
            39 => 
            array (
                'id' => 42,
                'audit_form_id' => 10,
                'file' => 'audit_form_files/F9i3oUxpWvRazyxkWUwK5RJVqNdoKTBXrLbV2djp.pdf',
                'file_type' => 'na',
                'file_name' => 'Edris Malya.pdf',
                'file_size' => '394165',
                'file_ext' => 'pdf',
                'uploaded_by' => 3,
                'created_at' => '2023-02-06 09:08:30',
                'updated_at' => '2023-02-06 09:08:30',
            ),
        ));
        
        
    }
}