<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class NormalAuditsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('normal_audits')->delete();
        
        \DB::table('normal_audits')->insert(array (
            0 => 
            array (
                'id' => 1,
                'auditor_team_id' => 1,
                'fiscal_year' => 2020,
                'audit_start_date' => '2023-01-23',
                'audit_end_date' => '2023-01-24',
                'sent_to_governor_date' => '2023-01-23',
                'total_pages' => 20,
                'confidentiality_level_id' => 2,
                'governor_office_remarks' => '<p>This is governor remarks</p>',
                'sent_to_governor' => 0,
                'file_location' => 'file location 1',
                'file_version' => 'v1',
                'file_manual_sequence_number' => '2',
                'role_id' => 1,
                'reported_by' => 3,
                'last_updated_by' => 0,
                'last_seen_by' => 0,
                'reviewed_by' => 3,
                'reviewed_by_date' => '2023-02-01',
                'approved_by' => 3,
                'approved_by_date' => '2023-02-04',
                'status' => 'Approved',
                'created_at' => '2023-01-24 12:00:16',
                'updated_at' => '2023-02-04 10:34:05',
            ),
            1 => 
            array (
                'id' => 2,
                'auditor_team_id' => 1,
                'fiscal_year' => 2020,
                'audit_start_date' => '2023-01-23',
                'audit_end_date' => '2023-01-24',
                'sent_to_governor_date' => '2023-01-24',
                'total_pages' => 2,
                'confidentiality_level_id' => 2,
                'governor_office_remarks' => '<p>ihiuihuihiuh</p>',
                'sent_to_governor' => 1,
                'file_location' => 'loj',
                'file_version' => 'v1',
                'file_manual_sequence_number' => '1',
                'role_id' => 1,
                'reported_by' => 1,
                'last_updated_by' => 0,
                'last_seen_by' => 0,
                'reviewed_by' => 3,
                'reviewed_by_date' => '2023-02-02',
                'approved_by' => 3,
                'approved_by_date' => '2023-02-02',
                'status' => 'Approved',
                'created_at' => '2023-01-24 12:16:11',
                'updated_at' => '2023-02-02 10:28:55',
            ),
            2 => 
            array (
                'id' => 3,
                'auditor_team_id' => 1,
                'fiscal_year' => 1990,
                'audit_start_date' => '2023-01-24',
                'audit_end_date' => '2023-01-24',
                'sent_to_governor_date' => '2023-01-24',
                'total_pages' => 2,
                'confidentiality_level_id' => 2,
                'governor_office_remarks' => '<p>test</p>',
                'sent_to_governor' => 1,
                'file_location' => 'Localtion',
                'file_version' => 'v1',
                'file_manual_sequence_number' => '2',
                'role_id' => 1,
                'reported_by' => 9,
                'last_updated_by' => 0,
                'last_seen_by' => 0,
                'reviewed_by' => 0,
                'reviewed_by_date' => NULL,
                'approved_by' => 0,
                'approved_by_date' => NULL,
                'status' => 'new',
                'created_at' => '2023-01-24 14:54:53',
                'updated_at' => '2023-01-24 14:54:53',
            ),
            3 => 
            array (
                'id' => 4,
                'auditor_team_id' => 1,
                'fiscal_year' => 1971,
                'audit_start_date' => '2023-01-26',
                'audit_end_date' => '2023-01-26',
                'sent_to_governor_date' => '2023-01-26',
                'total_pages' => 96,
                'confidentiality_level_id' => 2,
                'governor_office_remarks' => '<p>Delectus, adipisci a.</p>',
                'sent_to_governor' => 1,
                'file_location' => 'Quisquam similique c',
                'file_version' => 'Nihil et ab deserunt',
                'file_manual_sequence_number' => '738',
                'role_id' => 1,
                'reported_by' => 3,
                'last_updated_by' => 0,
                'last_seen_by' => 0,
                'reviewed_by' => 3,
                'reviewed_by_date' => '2023-02-02',
                'approved_by' => 3,
                'approved_by_date' => '2023-02-02',
                'status' => 'Approved',
                'created_at' => '2023-01-26 09:36:34',
                'updated_at' => '2023-02-02 10:31:20',
            ),
            4 => 
            array (
                'id' => 5,
                'auditor_team_id' => 1,
                'fiscal_year' => 2021,
                'audit_start_date' => '2023-02-01',
                'audit_end_date' => '2023-02-02',
                'sent_to_governor_date' => '2023-02-02',
                'total_pages' => 20,
                'confidentiality_level_id' => 2,
                'governor_office_remarks' => '<p>test</p>',
                'sent_to_governor' => 0,
                'file_location' => 'Locaiton',
                'file_version' => 'v1',
                'file_manual_sequence_number' => '2',
                'role_id' => 1,
                'reported_by' => 3,
                'last_updated_by' => 0,
                'last_seen_by' => 0,
                'reviewed_by' => 3,
                'reviewed_by_date' => '2023-02-04',
                'approved_by' => 0,
                'approved_by_date' => NULL,
                'status' => 'Reviewed',
                'created_at' => '2023-02-02 11:50:10',
                'updated_at' => '2023-02-04 14:26:34',
            ),
            5 => 
            array (
                'id' => 6,
                'auditor_team_id' => 1,
                'fiscal_year' => 2021,
                'audit_start_date' => '2023-02-04',
                'audit_end_date' => '2023-02-04',
                'sent_to_governor_date' => '2023-02-11',
                'total_pages' => 23,
                'confidentiality_level_id' => 2,
                'governor_office_remarks' => '<p>test</p>',
                'sent_to_governor' => 0,
                'file_location' => 'Locaiton',
                'file_version' => 'v1',
                'file_manual_sequence_number' => '2',
                'role_id' => 1,
                'reported_by' => 3,
                'last_updated_by' => 0,
                'last_seen_by' => 0,
                'reviewed_by' => 0,
                'reviewed_by_date' => NULL,
                'approved_by' => 0,
                'approved_by_date' => NULL,
                'status' => 'new',
                'created_at' => '2023-02-04 15:07:59',
                'updated_at' => '2023-02-04 15:07:59',
            ),
            6 => 
            array (
                'id' => 7,
                'auditor_team_id' => 1,
                'fiscal_year' => 2022,
                'audit_start_date' => '2023-02-06',
                'audit_end_date' => '2023-02-06',
                'sent_to_governor_date' => '2023-02-06',
                'total_pages' => 20,
                'confidentiality_level_id' => 2,
                'governor_office_remarks' => '<p>test</p>',
                'sent_to_governor' => 0,
                'file_location' => 'location',
                'file_version' => 'v1',
                'file_manual_sequence_number' => '2',
                'role_id' => 1,
                'reported_by' => 3,
                'last_updated_by' => 0,
                'last_seen_by' => 0,
                'reviewed_by' => 0,
                'reviewed_by_date' => NULL,
                'approved_by' => 0,
                'approved_by_date' => NULL,
                'status' => 'new',
                'created_at' => '2023-02-05 09:42:44',
                'updated_at' => '2023-02-05 09:42:44',
            ),
            7 => 
            array (
                'id' => 8,
                'auditor_team_id' => 1,
                'fiscal_year' => 2020,
                'audit_start_date' => '2023-02-05',
                'audit_end_date' => '2023-02-05',
                'sent_to_governor_date' => '2023-02-05',
                'total_pages' => 20,
                'confidentiality_level_id' => 2,
                'governor_office_remarks' => '<p>Test remarks	</p>',
                'sent_to_governor' => 1,
                'file_location' => 'location',
                'file_version' => 'v2',
                'file_manual_sequence_number' => '2',
                'role_id' => 1,
                'reported_by' => 3,
                'last_updated_by' => 0,
                'last_seen_by' => 0,
                'reviewed_by' => 0,
                'reviewed_by_date' => NULL,
                'approved_by' => 0,
                'approved_by_date' => NULL,
                'status' => 'new',
                'created_at' => '2023-02-05 14:50:03',
                'updated_at' => '2023-02-05 14:50:03',
            ),
            8 => 
            array (
                'id' => 9,
                'auditor_team_id' => 1,
                'fiscal_year' => 2022,
                'audit_start_date' => '2023-02-05',
                'audit_end_date' => '2023-02-05',
                'sent_to_governor_date' => '2023-01-01',
                'total_pages' => 2,
                'confidentiality_level_id' => 2,
                'governor_office_remarks' => '<p>test</p>',
                'sent_to_governor' => 0,
                'file_location' => 'l2',
                'file_version' => 'v2',
                'file_manual_sequence_number' => '3',
                'role_id' => 1,
                'reported_by' => 3,
                'last_updated_by' => 0,
                'last_seen_by' => 0,
                'reviewed_by' => 0,
                'reviewed_by_date' => NULL,
                'approved_by' => 0,
                'approved_by_date' => NULL,
                'status' => 'new',
                'created_at' => '2023-02-05 15:19:37',
                'updated_at' => '2023-02-05 15:19:37',
            ),
            9 => 
            array (
                'id' => 10,
                'auditor_team_id' => 1,
                'fiscal_year' => 2020,
                'audit_start_date' => '2023-02-09',
                'audit_end_date' => '2023-02-28',
                'sent_to_governor_date' => '2021-01-01',
                'total_pages' => 20,
                'confidentiality_level_id' => 2,
                'governor_office_remarks' => '<p>this is description</p>',
                'sent_to_governor' => 1,
                'file_location' => 'file location',
                'file_version' => 'v3',
                'file_manual_sequence_number' => '9',
                'role_id' => 1,
                'reported_by' => 3,
                'last_updated_by' => 0,
                'last_seen_by' => 0,
                'reviewed_by' => 3,
                'reviewed_by_date' => '2023-02-06',
                'approved_by' => 3,
                'approved_by_date' => '2023-02-06',
                'status' => 'Approved',
                'created_at' => '2023-02-06 09:08:28',
                'updated_at' => '2023-02-06 09:10:41',
            ),
        ));
        
        
    }
}